[build]
  command = "npm run build"
  publish = "build"
  environment = { REACT_APP_BACKEND_URL = "https://blocklygame-backend.onrender.com" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
